WIDTH = 800
HEIGHT = 800
MARGINS = 50
START_CELL_COUNT = 150
RANDOM_DELTA_POSITION = 20

START_MIN_AGING = 1
START_MAX_AGING = 5
RANDOM_DELTA_AGING = 5

GRID_ROWS = 10
GRID_COLS = 10
MAX_DENSITY_IN_CELL = 35
MIN_DENSITY_IN_CELL = 3
DENSITY_AGING_WEIGHT = 0.7

MIN_LIFE_SECONDS = 5
MAX_LIFE_SECONDS = 20